var staticT6Lib = window.ZBJInfo.newStaticLibURI;
if ( !staticT6Lib ) {
    staticT6Lib = 'http://t6.zbjimg.com';
}

seajs.config({
    debug: false,
    paths: {
        "components": staticT6Lib + '/output/components',
        "arale": staticT6Lib + '/arale',
        "zbj":  staticT6Lib + '/zbj',
        "gallery":  staticT6Lib + '/gallery'
    },
    alias: {
        "seajs-debug": "seajs/seajs-debug/1.1.1/seajs-debug",
        "widget":'arale/widget/1.1.1/widget',

        "position":'arale/position/1.0.1/position',
        "cookie":'arale/cookie/1.0.2/cookie',
        "sticky":'arale/sticky/1.3.1/sticky',

        //switchable
        "tabs":'arale/switchable/1.0.3/tabs',
        "slide": 'arale/switchable/1.0.3/slide',
        "accordion": 'arale/switchable/1.0.3/accordion',
        "carousel": 'arale/switchable/1.0.3/carousel',
        "overlay": 'arale/overlay/1.1.3/overlay',
        "mask": 'arale/overlay/1.1.3/mask',
        "dialog": 'arale/dialog/1.3.0/dialog',
        "events": 'arale/events/1.1.0/events',

        "validator":'arale/validator/0.9.7/validator',

        "autocomplete":'arale/autocomplete/1.2.3/autocomplete',

        "tpl": 'arale/templatable/0.9.2/templatable',

        // zbj
        "verifycode":'zbj/verifycode/1.1.0/verifycode',
        "address-selector":'zbj/address-selector/1.0.0/index',

        "backbone": 'components/backbone/index',
        "underscore": 'components/underscore/index'
    }
});
if ( window.$ ) {
    define('hack$', [], function(){ return window.$; });
    seajs.use('hack$');
    seajs.cache[seajs.resolve('$')] = seajs.cache[seajs.resolve('$-debug')] =
        seajs.cache[seajs.resolve('jquery')] = seajs.cache[seajs.resolve('jquery-debug')] = seajs.cache[seajs.resolve('hack$')];
}

var _oldSeajsModuleResolve = seajs.Module.resolve;

// output 后，seajs resolve 后再 map 的路径错误
seajs.Module.resolve = function(){
    var url = _oldSeajsModuleResolve.apply(this, arguments);
    return url.replace('output/output/', 'output/');
};

// map config bellow is auto generated by build system
seajs.config({
    map:[
        ["global/global.js", "output/global/global.js?2a73906585e97c1e"],
        ["index/diy.js", "output/index/diy.js?28ef2cdc1b54d5ac"],
        ["index/floor.js", "output/index/floor.js?a5a8b673cf841ce6"],
        ["index/index.js", "output/index/index.js?fb0805e6f48f5661"],
        ["index2015/index.js", "output/index2015/index.js?84fc979284662a58"],
        ["logo/detail.tpl.js", "output/logo/detail.tpl.js?82f951fd92307c81"],
        ["logo/index.js", "output/logo/index.js?a9828af05155d4bd"],
        ["reward/fontscroll.js", "output/reward/fontscroll.js?0f8f5619abaebc16"],
        ["reward/index.js", "output/reward/index.js?a164bd3190c121fc"],
        ["role/main.js", "output/role/main.js?191a15c92a24d463"],
        ["story/article.js", "output/story/article.js?95de032e5b332638"],
        ["story/category.js", "output/story/category.js?3907c0cd8f9fbe18"],
        ["story/common.js", "output/story/common.js?1dcd5ab9c061b6eb"],
        ["story/face.js", "output/story/face.js?2fd1050edd32a1f1"],
        ["story/home.js", "output/story/home.js?cb62fc5eecfad6db"],
        ["story/list.js", "output/story/list.js?0585c09d34198f4e"],
        ["story/pub.js", "output/story/pub.js?502495ae0176001f"],
        ["tuiguangtong/highcharts.js", "output/tuiguangtong/highcharts.js?9b96785a55bca2e1"],
        ["tuiguangtong/tuiguangtong.js", "output/tuiguangtong/tuiguangtong.js?4fac785fe7099f41"],
        ["components/address-selector/index.js", "output/components/address-selector/index.js?05447abb9fe04854"],
        ["components/backbone/index.js", "output/components/backbone/index.js?62f8e0123f5a5772"],
        ["components/baidutemplate/baidutemplate.js", "output/components/baidutemplate/baidutemplate.js?489cfc6530d927b1"],
        ["components/captchable/captcha.tpl.js", "output/components/captchable/captcha.tpl.js?22a8c9ff0ba01ed0"],
        ["components/captchable/captchable.js", "output/components/captchable/captchable.js?295a2c3e8b57b9a8"],
        ["components/employ-dialog/employ.tpl.js", "output/components/employ-dialog/employ.tpl.js?06e3113824862884"],
        ["components/employ-dialog/index.js", "output/components/employ-dialog/index.js?bc3d856331ac97d5"],
        ["components/loading/loading.js", "output/components/loading/loading.js?56c5cab27f41f8e8"],
        ["components/loginable/apply.tpl.js", "output/components/loginable/apply.tpl.js?9e5c3515d45a6eff"],
        ["components/loginable/loginable.js", "output/components/loginable/loginable.js?5c462313d61a9cf3"],
        ["components/loginable/loginable.tpl.js", "output/components/loginable/loginable.tpl.js?5dd929a4268fb928"],
        ["components/loginable/loginable2.tpl.js", "output/components/loginable/loginable2.tpl.js?3f768b5fc92256c9"],
        ["components/logo-upload/delete.js", "output/components/logo-upload/delete.js?d5efc2f5e38d651e"],
        ["components/logo-upload/delete.tpl.js", "output/components/logo-upload/delete.tpl.js?b990b6fb244fbe1b"],
        ["components/logo-upload/logo-upload.js", "output/components/logo-upload/logo-upload.js?28a0a76a09924b60"],
        ["components/logo-upload/logoupload.tpl.js", "output/components/logo-upload/logoupload.tpl.js?3467ecdc2725ad14"],
        ["components/logo-upload/preview.tpl.js", "output/components/logo-upload/preview.tpl.js?56d11d0cb36526fa"],
        ["components/paidan-tip/paidan-tip-countdown.tpl.js", "output/components/paidan-tip/paidan-tip-countdown.tpl.js?f3396b029035d952"],
        ["components/paidan-tip/paidan-tip.js", "output/components/paidan-tip/paidan-tip.js?628fa575af848ddc"],
        ["components/paidan-tip/paidan-tip.tpl.js", "output/components/paidan-tip/paidan-tip.tpl.js?db30000d767c876b"],
        ["components/requirement-publish/CacheUtil.js", "output/components/requirement-publish/CacheUtil.js?185833a782f9acf8"],
        ["components/requirement-publish/CrossDomainUtil.js", "output/components/requirement-publish/CrossDomainUtil.js?6ce48816995b0c1d"],
        ["components/requirement-publish/UrlUtil.js", "output/components/requirement-publish/UrlUtil.js?9679129a0bcccb46"],
        ["components/requirement-publish/index.js", "output/components/requirement-publish/index.js?70f6fdb840152e9c"],
        ["components/underscore/index.js", "output/components/underscore/index.js?abd1ee20c19eed35"],
        ["components/up/up.tpl.js", "output/components/up/up.tpl.js?766ab34b2b228180"],
        ["components/uploader/index.js", "output/components/uploader/index.js?ea8803a5a79c3814"],
        ["components/utils/utils.js", "output/components/utils/utils.js?a5c3dadd0a5ca25c"],
        ["global/js/menu.js", "output/global/js/menu.js?e45068bd4ff253d1"],
        ["global/js/msg.js", "output/global/js/msg.js?c9e504119b68da9b"],
        ["global/js/refreshtopbar.js", "output/global/js/refreshtopbar.js?ce79d47e377f5165"],
        ["index2015/js/tab.js", "output/index2015/js/tab.js?4976e2ed3d2a6f30"],
        ["jquery/ie6hover/ie6hover.js", "output/jquery/ie6hover/ie6hover.js?9205116167203e6d"],
        ["jquery/lazyload/jquery.lazyload.js", "output/jquery/lazyload/jquery.lazyload.js?bf74be17ed84a045"],
        ["jquery/menuaim/jquery.menu-aim.js", "output/jquery/menuaim/jquery.menu-aim.js?92a25fbc11c65445"],
        ["jquery/respond/respond.min.js", "output/jquery/respond/respond.min.js?c798fc9742e5431f"],
        ["role/js/tab.js", "output/role/js/tab.js?4d55742ee7e8e696"],
        ["task/bang/index.js", "output/task/bang/index.js?317e84d0f91fe32f"],
        ["components/requirement-publish/controller/AppRouter.js", "output/components/requirement-publish/controller/AppRouter.js?7b345a92e5d7801b"],
        ["components/requirement-publish/models/Category.js", "output/components/requirement-publish/models/Category.js?01f3b3eb2804e7bc"],
        ["components/requirement-publish/models/Contact.js", "output/components/requirement-publish/models/Contact.js?a4ea285e13815948"],
        ["components/requirement-publish/models/Detail.js", "output/components/requirement-publish/models/Detail.js?a27dc71a0f1d17de"],
        ["components/requirement-publish/models/Other.js", "output/components/requirement-publish/models/Other.js?353d923ad3a449e3"],
        ["components/requirement-publish/models/Title.js", "output/components/requirement-publish/models/Title.js?59f29ab577af448e"],
        ["components/requirement-publish/models/Tradepay.js", "output/components/requirement-publish/models/Tradepay.js?ba9e3603b1c54e7c"],
        ["components/requirement-publish/tpls/category-edit.u.tpl.js", "output/components/requirement-publish/tpls/category-edit.u.tpl.js?c364f8ce2a258bf4"],
        ["components/requirement-publish/tpls/category-ext.u.tpl.js", "output/components/requirement-publish/tpls/category-ext.u.tpl.js?b9ca8b0448fac1ac"],
        ["components/requirement-publish/tpls/category-save.u.tpl.js", "output/components/requirement-publish/tpls/category-save.u.tpl.js?a47c67e9009f991e"],
        ["components/requirement-publish/tpls/contact-edit.u.tpl.js", "output/components/requirement-publish/tpls/contact-edit.u.tpl.js?c8f1e7080f607eb2"],
        ["components/requirement-publish/tpls/contact-save.u.tpl.js", "output/components/requirement-publish/tpls/contact-save.u.tpl.js?f279e533eb80c53d"],
        ["components/requirement-publish/tpls/detail-edit.u.tpl.js", "output/components/requirement-publish/tpls/detail-edit.u.tpl.js?96d40739c07b8ec5"],
        ["components/requirement-publish/tpls/detail-save.u.tpl.js", "output/components/requirement-publish/tpls/detail-save.u.tpl.js?6565f409439804b0"],
        ["components/requirement-publish/tpls/other.u.tpl.js", "output/components/requirement-publish/tpls/other.u.tpl.js?7653dcb118807b7b"],
        ["components/requirement-publish/tpls/requirement.u.tpl.js", "output/components/requirement-publish/tpls/requirement.u.tpl.js?6b6b8a6f0a286f2e"],
        ["components/requirement-publish/tpls/title.u.tpl.js", "output/components/requirement-publish/tpls/title.u.tpl.js?6d56665061767caf"],
        ["components/requirement-publish/tpls/trade-pay-edit.u.tpl.js", "output/components/requirement-publish/tpls/trade-pay-edit.u.tpl.js?c4732d3d3c322f49"],
        ["components/requirement-publish/tpls/trade-pay-save.u.tpl.js", "output/components/requirement-publish/tpls/trade-pay-save.u.tpl.js?e45cc79ff19c7293"],
        ["components/requirement-publish/views/AppView.js", "output/components/requirement-publish/views/AppView.js?cc1c69b55645f6d7"],
        ["components/requirement-publish/views/CategoryView.js", "output/components/requirement-publish/views/CategoryView.js?71e8649df7f57f3b"],
        ["components/requirement-publish/views/ContactView.js", "output/components/requirement-publish/views/ContactView.js?c6a092303fbfdcec"],
        ["components/requirement-publish/views/DetailView.js", "output/components/requirement-publish/views/DetailView.js?ea024dc218657a28"],
        ["components/requirement-publish/views/EventAcrossView.js", "output/components/requirement-publish/views/EventAcrossView.js?b36fd2a3a7b03619"],
        ["components/requirement-publish/views/OtherView.js", "output/components/requirement-publish/views/OtherView.js?c29c78bfa19b1e27"],
        ["components/requirement-publish/views/TitleView.js", "output/components/requirement-publish/views/TitleView.js?5ad66c8b7687ec01"],
        ["components/requirement-publish/views/TradepayView.js", "output/components/requirement-publish/views/TradepayView.js?8c8ec5f0c53316d9"],
        ["components/uploader/plupload/plupload.full.min.js", "output/components/uploader/plupload/plupload.full.min.js?1cefef0dd4ba9e50"],
        ["components/captchable/captcha.css", "output/components/captchable/captcha.css?89277bd559f6c832"],
        ["components/employ-dialog/index.css", "output/components/employ-dialog/index.css?c3b91d52647008e4"],
        ["components/logo-upload/delete.css", "output/components/logo-upload/delete.css?4080a33d052d2d36"],
        ["components/logo-upload/logo-upload.css", "output/components/logo-upload/logo-upload.css?ddac8fc1f5346798"],
        ["components/paidan-tip/paidan-tip.css", "output/components/paidan-tip/paidan-tip.css?d79fc161f34f90e3"],
        ["components/requirement-publish/index.css", "output/components/requirement-publish/index.css?5170bc118f03ecdc"],
        ["components/uploader/index.css", "output/components/uploader/index.css?37ed3650228fb37b"]
    ]
});